version: '2'
services:
  db:
    image: mongo
    ports:
      - "27017:27017"
  web:
    build: .
    ports:
      - "80:80"
    environment:
      - API_HOST=web-demo-api-staging-codenow.runnablecloud.com:3000
  api:
    build: 
      context: git@github.com:CodeNow/api-demo
    ports:
      - "3000:3000"
    environment:
      - MONGODB_HOST=db
