version: '2'
services:
  db:
    image: mongo
    ports:
      - "27017:27017"
  chrome:
    image: selenium/standalone-chrome
    ports:
      - "4444:4444"
  api:
    build: 
      context: git@github.com:CodeNow/api-demo
    ports:
      - "3000:3000"
    environment:
      - MONGODB_HOST=db
  web:
    build: .
    ports:
      - "80:80"
    environment:
      - API_HOST=web-demp-api-staging-codenow.runnablecloud.com:3000
  e2e:
    build: 
      context: git@github.com:CodeNow/e2e-demo
    environment:
      - WEB_URL=http://web
      - NODE_ENV=docker
